framework:
    messenger:
        # failure_transport: failed

        transports:
            azure_service_bus:
                serializer: messenger.transport.symfony_serializer
                dsn: 'custom://'
                options:
                    endpoint: '%env(AZURE_SERVICE_BUS_ENDPOINT)%'
                    sasKeyName: '%env(AZURE_SERVICE_BUS_SAS_KEY_NAME)%'
                    sasKeyValue: '%env(AZURE_SERVICE_BUS_SAS_KEY_VALUE)%'
                    queue: '%env(AZURE_SERVICE_BUS_QUEUE)%'
            # failed: 'doctrine://default?queue_name=failed'xs
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            'App\Message\ImageToProcess': azure_service_bus
