controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


photo_index:
    path: /photos
    controller: App\Controller\PhotoController::index

photos_new:
    path: /photos/new
    controller: App\Controller\PhotoController::new


